backend:
  name: git-gateway
  branch: cms
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: static/img
public_folder: /img

collections:
  - name: "members"
    label: "Members"
    folder: "src/pages/members"
    description: "These are the members currently in WIB."
    slug: "{{andrewID}}"
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "member",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "AndrewID", name: "andrewID", widget: "string" }
      - { label: "Role", name: "role", widget: "string" }
      - { label: "Description", name: "description", widget: "text"}
      - { label: "Photo", name: "photo", widget: image }
      - { label: "Portfolio", name: "portfolio", widget: "markdown" }
      - { label: "Resume", name: "resume", widget: "file" }
      - { label: "Year", name: "year", widget: "number", value_type: "int" }
      - { label: "Degree", name: "degree", widget: "select", options: ["BS", "MS"] }
      - { label: "Major", name: "major", widget: "string" }
      - { label: "LinkedIn", name: "linkedIn", widget: "string" }

  - name: "events"
    label: "Events"
    folder: "src/pages/events"
    description: "These are the current events for CMU WIB."
    slug: "{{title}}"
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "event",
        }
      - { label: "Photo", name: "photo", widget: image }
